## Multi strategy time
### Scalping
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/scalping \
  --forward-start 2025-01-01 \
  --score-col "score_scalp__multi_strategy_time__rank_hgb__scalp" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.6 \
  --min-traded-value 500000000 \
  --require-broksum 

### Swing defensive `0.161`
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/swing_hgb_defensive \
  --forward-start 2025-01-01 \
  --score-col "score_swing__multi_strategy_time__hgb__swing" \
  --top-k 15 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly

### swing aggresive `0.485`
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/swing_hgb_aggresive \
  --forward-start 2025-01-01 \
  --score-col "score_swing__multi_strategy_time__xgb__swing" \
  --top-k 15 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 1000000000 \
  --require-broksum

### Position `0.117`
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/position \
  --forward-start 2025-01-01 \
  --score-col "score_position__multi_strategy_time__xgb__position" \
  --top-k 15 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 1000000000 \
  --require-broksum


## ARA predictor
### More safe and risk `0.511`
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/ara_candidate \
  --forward-start 2025-01-01 \
  --score-col "score_ara" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 1000000000 \
  --require-broksum

### Very high risk `0.870`
  python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/ara_watchlist_only \
  --forward-start 2025-01-01 \
  --score-col "score_ara__ara_predictor__xgb__ara_tomorrow" \
  --top-k 1 \
  --hold-days 5 \
  --min-score 0.55 \
  --min-traded-value 500000000 \
  --require-broksum


## Momentum ranker
### Momentum 5d defensif
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_5d_hgb_defensif \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_5d__momentum_ranker__xgb__momentum_5d" \
  --top-k 2 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 2000000000 \
  --require-broksum


### Momentum 5d aggresive
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_5d_hgb-aggresive \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_5d__momentum_ranker__regime_hgb__momentum_5d" \
  --top-k 7 \
  --hold-days 2 \
  --min-score 0.60 \
  --min-traded-value 500000000 \
  --require-broksum


### Momentum 10d defensif
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_ranker_10d_defensif \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_10d__momentum_ranker__xgb__momentum_10d" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 2000000000

### Momentum 10d aggresive
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_ranker_10d_aggresive \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_10d__momentum_ranker__hgb__momentum_10d" \
  --top-k 15 \
  --hold-days 2 \
  --min-score 0.60 \
  --min-traded-value 500000000 \
  --require-broksum


## Market Maker
### silent_accum_breakout defensif
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/market_maker_silent_accum_defensif \
  --forward-start 2025-01-01 \
  --score-col "score_mm_silent" \
  --top-k 7 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 1000000000 \
  --require-broksum


### silent_accum_breakout aggresive
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/market_maker_silent_accum_aggresive \
  --forward-start 2025-01-01 \
  --score-col "score_mm_silent__market_maker_accumulation__xgb__silent_accum_breakout" \
  --top-k 3 \
  --hold-days 2 \
  --min-score 0.50 \
  --min-traded-value 500000000 \
  --exclude-broker-value-anomaly

ARA == ARA CANDIDATE:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/ara_candidate \
  --forward-start 2025-01-01 \
  --score-col "score_ara" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 1000000000 \
  --require-broksum

MARKET MAKER == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/market_maker_silent_accum_defensif \
  --forward-start 2025-01-01 \
  --score-col "score_mm_silent" \
  --top-k 7 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 1000000000 \
  --require-broksum


MOMENTUM RANKER 5D == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_5d_hgb_defensif \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_5d__momentum_ranker__xgb__momentum_5d" \
  --top-k 2 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 2000000000 \
  --require-broksum

MOMENTUM RANKER 10D == AGGRESIVE:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/momentum_ranker_10d_aggresive \
  --forward-start 2025-01-01 \
  --score-col "score_momentum_10d__momentum_ranker__hgb__momentum_10d" \
  --top-k 15 \
  --hold-days 2 \
  --min-score 0.60 \
  --min-traded-value 500000000 \
  --require-broksum
  

MULTI STRATEGY SCALPING:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/scalping \
  --forward-start 2025-01-01 \
  --score-col "score_scalp__multi_strategy_time__rank_hgb__scalp" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.6 \
  --min-traded-value 500000000 \
  --require-broksum 

MULTI STRATEGY SWING == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/swing_hgb_defensive \
  --forward-start 2025-01-01 \
  --score-col "score_swing__multi_strategy_time__hgb__swing" \
  --top-k 15 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly

MULTI STRATEGY POSITION:
python3 workflows/run_forward_test.py \
  --panel signals/validation/validation_signal_panel.parquet \
  --output-dir data/evaluation/forward_tests/position \
  --forward-start 2025-01-01 \
  --score-col "score_position__multi_strategy_time__xgb__position" \
  --top-k 15 \
  --hold-days 1 \
  --min-score 0.55 \
  --min-traded-value 1000000000 \
  --require-broksum

# Monte carlo:
1. ARA
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/ara_candidate/trades.parquet \
  --output-dir data/evaluation/monte_carlo/ara_candidate \
  --n-iter 5000

2. Market Maker
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/market_maker_silent_accum_defensif/trades.parquet \
  --output-dir data/evaluation/monte_carlo/market_maker_silent_accum_defensif \
  --n-iter 5000

3. Momentum 5D
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/momentum_5d_hgb_defensif/trades.parquet \
  --output-dir data/evaluation/monte_carlo/momentum_5d_hgb_defensif \
  --n-iter 5000

4. Momentum 10D
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/momentum_ranker_10d_aggresive/trades.parquet \
  --output-dir data/evaluation/monte_carlo/momentum_ranker_10d_aggresive \
  --n-iter 5000

5. Scalping
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/scalping/trades.parquet \
  --output-dir data/evaluation/monte_carlo/scalping \
  --n-iter 5000

6. Swing
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/swing_hgb_defensive/trades.parquet \
  --output-dir data/evaluation/monte_carlo/swing_hgb_defensive \
  --n-iter 5000

7. Position
python3 workflows/run_monte_carlo.py \
  --trades data/evaluation/forward_tests/position/trades.parquet \
  --output-dir data/evaluation/monte_carlo/position \
  --n-iter 5000

# Rolling Back / Continual Learning `Backtest Search`

In [5]:
import polars as pl

df = pl.read_parquet("/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/features/live/latest/base_features.parquet")

recent = (
    df.filter(pl.col("date") >= pl.date(2026, 5, 19))
    .group_by("date")
    .agg([
        pl.len().alias("initial"),
        pl.col("close").is_not_null().sum().alias("valid_close"),
        ((pl.col("close") >= 100) & (pl.col("close") <= 1000)).sum().alias("price_100_1000"),
        (pl.col("traded_value_proxy").fill_null(0) >= 500_000_000).sum().alias("min_traded_value"),
        (pl.col("has_broksum").fill_null(0) == 1).sum().alias("has_broksum"),
        (
            (pl.col("close").is_not_null()) &
            (pl.col("close") >= 100) &
            (pl.col("close") <= 1000) &
            (pl.col("traded_value_proxy").fill_null(0) >= 500_000_000) &
            (pl.col("has_broksum").fill_null(0) == 1)
        ).sum().alias("final_eligible"),
    ])
    .sort("date")
)

print(recent)

shape: (2, 7)
┌────────────┬─────────┬─────────────┬───────────────┬───────────────┬─────────────┬───────────────┐
│ date       ┆ initial ┆ valid_close ┆ price_100_100 ┆ min_traded_va ┆ has_broksum ┆ final_eligibl │
│ ---        ┆ ---     ┆ ---         ┆ 0             ┆ lue           ┆ ---         ┆ e             │
│ date       ┆ u32     ┆ u32         ┆ ---           ┆ ---           ┆ u32         ┆ ---           │
│            ┆         ┆             ┆ u32           ┆ u32           ┆             ┆ u32           │
╞════════════╪═════════╪═════════════╪═══════════════╪═══════════════╪═════════════╪═══════════════╡
│ 2026-05-19 ┆ 959     ┆ 959         ┆ 516           ┆ 482           ┆ 863         ┆ 252           │
│ 2026-05-20 ┆ 959     ┆ 959         ┆ 522           ┆ 449           ┆ 858         ┆ 231           │
└────────────┴─────────┴─────────────┴───────────────┴───────────────┴─────────────┴───────────────┘

## ARA == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/ara_candidate \
  --forward-start 2026-01-20 \
  --score-col "score_ara" \
  --top-k 7 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly


## ARA == AGGRESIVE:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/ara_watchlist \
  --forward-start 2026-01-20 \
  --score-col "score_ara__ara_predictor__hgb__ara_tomorrow" \
  --top-k 1 \
  --hold-days 1 \
  --min-score 0.50 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly

## MOMENTUM RANKER 5D == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/momentum_5d_hgb_defensif \
  --forward-start 2026-01-20 \
  --score-col "score_momentum_5d__momentum_ranker__regime_hgb__momentum_5d" \
  --top-k 10 \
  --hold-days 2 \
  --min-traded-value 1000000000 \
  --require-broksum


## MOMENTUM RANKER 10D == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/momentum_ranker_10d_aggresive \
  --forward-start 2026-01-20 \
  --score-col "score_momentum_10d__momentum_ranker__hgb__momentum_10d" \
  --top-k 7 \
  --hold-days 2 \
  --min-traded-value 1000000000 

## MOMENTUM RANKER 20D == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/momentum_ranker_20d_aggresive \
  --forward-start 2026-01-20 \
  --score-col "score_momentum_20d__momentum_ranker__regime_hgb__momentum_20d" \
  --top-k 5 \
  --hold-days 1 \
  --min-traded-value 2000000000 \
  --require-broksum 





## MULTI STRATEGY SCALPING == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/scalping \
  --forward-start 2026-01-20 \
  --score-col "score_scalp" \
  --top-k 3 \
  --hold-days 2 \
  --min-score 0.65 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly


## MULTI STRATEGY SWING == DEFENSIF:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/swing_hgb_defensive \
  --forward-start 2026-01-20 \
  --score-col "score_swing__multi_strategy_time__hgb__swing" \
  --top-k 7 \
  --hold-days 1 \
  --min-traded-value 500000000 \
  --require-broksum \
  --exclude-broker-value-anomaly

## MULTI STRATEGY POSITION:
python3 workflows/run_forward_test.py \
  --panel signals/validation/continual_q3_2024_q1_2026_panel_enriched.parquet \
  --output-dir data/evaluation/forward_tests/continual_learning/position \
  --forward-start 2026-01-20 \
  --score-col "score_position__multi_strategy_time__xgb__position" \
  --top-k 7 \
  --hold-days 2 \
  --min-score 0.55 \
  --min-traded-value 2000000000 \
  --require-broksum

In [4]:
import polars as pl

path = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/features/history/base_features.parquet"

df = pl.read_parquet(path)

print(df.shape)
print(df.head())
print(df.tail())
print(
    df.select([
        pl.col("date").min().alias("min_date"),
        pl.col("date").max().alias("max_date"),
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("duplicate_ticker_date"),
    ])
)

(1782675, 198)
shape: (5, 198)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ rank1_buye ┆ rank1_sel ┆ … ┆ rank1_buy ┆ rank1_sel ┆ rank1_sel ┆ rank1_sel │
│ ---        ┆ ---    ┆ r          ┆ ler       ┆   ┆ _freq     ┆ l_val     ┆ l_lot     ┆ l_freq    │
│ date       ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-01-04 ┆ AALI   ┆ DB         ┆ DB        ┆ … ┆ 53.0      ┆ 1.1233e10 ┆ 7086.0    ┆ 449.0     │
│ 2016-01-04 ┆ ABBA   ┆ LK         ┆ LK        ┆ … ┆ 1.0       ┆ 1.17e8    ┆ 26000.0   ┆ 1.0       │
│ 2016-01-04 ┆ ABDA   ┆ YU         ┆ YU        ┆ … ┆ 1.0       ┆ 750000.0  ┆ 1.0       ┆ 1.0       │
│ 2016-01-04 ┆ ABMM   ┆ YP         ┆ RF        ┆ … ┆ 2.0       ┆ 2.675e7   ┆ 100.0     ┆ 2.0       │
│ 2016-01-04 ┆ ACES   ┆ DB         ┆ CC        ┆ … ┆ 203.0     ┆ 1.6454e9  ┆ 20542.0   ┆ 79.0      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (5, 198)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ rank1_buye ┆ rank1_sel ┆ … ┆ rank1_buy ┆ rank1_sel ┆ rank1_sel ┆ rank1_sel │
│ ---        ┆ ---    ┆ r          ┆ ler       ┆   ┆ _freq     ┆ l_val     ┆ l_lot     ┆ l_freq    │
│ date       ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2025-12-30 ┆ ZATA   ┆ XL         ┆ XL        ┆ … ┆ 7699.0    ┆ 6.5898e9  ┆ 1.027835e ┆ 6462.0    │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ 2025-12-30 ┆ ZBRA   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025-12-30 ┆ ZINC   ┆ AZ         ┆ XL        ┆ … ┆ 11.0      ┆ 4.52792e7 ┆ 14256.0   ┆ 111.0     │
│ 2025-12-30 ┆ ZONE   ┆ XL         ┆ XL        ┆ … ┆ 20.0      ┆ 3.371e6   ┆ 65.0      ┆ 26.0      │
│ 2025-12-30 ┆ ZYRX   ┆ XA         ┆ XL        ┆ … ┆ 32.0      ┆ 3.60534e7 ┆ 2182.0    ┆ 94.0      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 3)
┌────────────┬────────────┬───────────────────────┐
│ min_date   ┆ max_date   ┆ duplicate_ticker_date │
│ ---        ┆ ---        ┆ ---                   │
│ date       ┆ date       ┆ u32                   │
╞════════════╪════════════╪═══════════════════════╡
│ 2016-01-04 ┆ 2025-12-30 ┆ 0                     │
└────────────┴────────────┴───────────────────────┘

In [3]:
import pandas as pd

macro = pd.read_parquet("data/features/macro/macro_features.parquet")
macro.to_csv("mac.csv", index=False)

In [1]:
import polars as pl

m = pl.read_parquet("data/raw_canonical/macro.parquet")
mf = pl.read_parquet("data/features/macro/macro_features.parquet")

print(m.shape, m.columns[:30])
print(m.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.col("macro_missing_flag").fill_null(0).sum().alias("macro_missing_rows"),
]))

print(mf.shape, mf.columns[:50])
print(mf.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.col("macro_missing_flag").fill_null(0).sum().alias("macro_missing_rows"),
]))

(4158, 16) ['date', 'idr_usd', 'usd_idr', 'wti', 'brent', 'coal_proxy', 'ihsg', 'bi_rate', 'macro_missing_flag', 'coal_gap_flag', 'oil_avg', 'wti_return', 'brent_return', 'fx_return', 'coal_proxy_return', 'bi_rate_change']
shape: (1, 3)
┌────────────┬────────────┬────────────────────┐
│ min_date   ┆ max_date   ┆ macro_missing_rows │
│ ---        ┆ ---        ┆ ---                │
│ date       ┆ date       ┆ i64                │
╞════════════╪════════════╪════════════════════╡
│ 2015-01-01 ┆ 2026-05-20 ┆ 0                  │
└────────────┴────────────┴────────────────────┘
(4158, 74) ['date', 'idr_usd', 'usd_idr', 'wti', 'brent', 'coal_proxy', 'ihsg', 'bi_rate', 'macro_missing_flag', 'coal_gap_flag', 'oil_avg', 'wti_return', 'brent_return', 'fx_return', 'coal_proxy_return', 'bi_rate_change', 'market_ret_1d', 'idr_usd_ret_5d', 'idr_usd_vol_5d', 'brent_ret_5d', 'wti_ret_5d', 'oil_avg_ret_5d', 'brent_vol_5d', 'coal_ret_5d', 'coal_vol_5d', 'ihsg_ret_5d', 'idr_usd_ret_10d', 'idr_usd_vol_10d', 'brent_ret_10d', 'wti_ret_10d', 'oil_avg_ret_10d', 'brent_vol_10d', 'coal_ret_10d', 'coal_vol_10d', 'ihsg_ret_10d', 'idr_usd_ret_20d', 'idr_usd_vol_20d', 'brent_ret_20d', 'wti_ret_20d', 'oil_avg_ret_20d', 'brent_vol_20d', 'coal_ret_20d', 'coal_vol_20d', 'ihsg_ret_20d', 'idr_usd_ret_60d', 'idr_usd_vol_60d', 'brent_ret_60d', 'wti_ret_60d', 'oil_avg_ret_60d', 'brent_vol_60d']
shape: (1, 3)
┌────────────┬────────────┬────────────────────┐
│ min_date   ┆ max_date   ┆ macro_missing_rows │
│ ---        ┆ ---        ┆ ---                │
│ date       ┆ date       ┆ i64                │
╞════════════╪════════════╪════════════════════╡
│ 2015-01-01 ┆ 2026-05-20 ┆ 0                  │
└────────────┴────────────┴────────────────────┘

# Check EOD Updates

## Apakah live feature store sudah punya 2026-05-21?

In [1]:
import polars as pl

df = pl.read_parquet("data/features/live/latest/base_features.parquet")

print(df.shape)
print(df.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup"),
]))

(60389, 198)
shape: (1, 3)
┌────────────┬────────────┬─────┐
│ min_date   ┆ max_date   ┆ dup │
│ ---        ┆ ---        ┆ --- │
│ date       ┆ date       ┆ u32 │
╞════════════╪════════════╪═════╡
│ 2026-02-23 ┆ 2026-06-05 ┆ 0   │
└────────────┴────────────┴─────┘

## Feature store sudah punya 2026-05-21?

In [3]:
import polars as pl

df = pl.read_parquet("data/features/live/latest/base_features.parquet")

recent = (
    df.filter(pl.col("date") >= pl.date(2026, 5, 19))
    .group_by("date")
    .agg([
        pl.len().alias("initial"),
        pl.col("close").is_not_null().sum().alias("valid_close"),
        ((pl.col("close") >= 100) & (pl.col("close") <= 1000)).sum().alias("price_100_1000"),
        (pl.col("traded_value_proxy").fill_null(0) >= 500_000_000).sum().alias("min_traded_value"),
        (pl.col("has_broksum").fill_null(0) == 1).sum().alias("has_broksum"),
        (
            (pl.col("close").is_not_null()) &
            (pl.col("close") >= 100) &
            (pl.col("close") <= 1000) &
            (pl.col("traded_value_proxy").fill_null(0) >= 500_000_000) &
            (pl.col("has_broksum").fill_null(0) == 1)
        ).sum().alias("final_eligible"),
    ])
    .sort("date")
)

print(recent)

shape: (8, 7)
┌────────────┬─────────┬─────────────┬───────────────┬───────────────┬─────────────┬───────────────┐
│ date       ┆ initial ┆ valid_close ┆ price_100_100 ┆ min_traded_va ┆ has_broksum ┆ final_eligibl │
│ ---        ┆ ---     ┆ ---         ┆ 0             ┆ lue           ┆ ---         ┆ e             │
│ date       ┆ u32     ┆ u32         ┆ ---           ┆ ---           ┆ u32         ┆ ---           │
│            ┆         ┆             ┆ u32           ┆ u32           ┆             ┆ u32           │
╞════════════╪═════════╪═════════════╪═══════════════╪═══════════════╪═════════════╪═══════════════╡
│ 2026-05-19 ┆ 959     ┆ 959         ┆ 516           ┆ 482           ┆ 863         ┆ 252           │
│ 2026-05-20 ┆ 959     ┆ 959         ┆ 522           ┆ 449           ┆ 858         ┆ 231           │
│ 2026-05-21 ┆ 959     ┆ 959         ┆ 506           ┆ 454           ┆ 863         ┆ 225           │
│ 2026-05-22 ┆ 959     ┆ 959         ┆ 508           ┆ 409           ┆ 861         ┆ 203           │
│ 2026-05-25 ┆ 959     ┆ 959         ┆ 514           ┆ 391           ┆ 865         ┆ 192           │
│ 2026-05-26 ┆ 959     ┆ 959         ┆ 512           ┆ 381           ┆ 863         ┆ 197           │
│ 2026-05-29 ┆ 959     ┆ 959         ┆ 514           ┆ 362           ┆ 860         ┆ 184           │
│ 2026-06-02 ┆ 959     ┆ 959         ┆ 515           ┆ 383           ┆ 859         ┆ 200           │
└────────────┴─────────┴─────────────┴───────────────┴───────────────┴─────────────┴───────────────┘

## Canonical raw sudah punya 21 May atau belum?

In [2]:
import polars as pl

for p in [
    "data/raw_canonical/ohlcv.parquet",
    "data/raw_canonical/broker_summary.parquet",
    "data/raw_canonical/insider_activity.parquet",
    "data/raw_canonical/neo_bdm.parquet",
    "data/raw_canonical/tradebook_price.parquet",
    "data/raw_canonical/macro.parquet",
    "data/raw_canonical/tradebook_time.parquet",
]:
    df = pl.read_parquet(p)
    print(p, df.shape, df.select([
        pl.col("date").min().alias("min"),
        pl.col("date").max().alias("max"),
    ]))

data/raw_canonical/ohlcv.parquet (1956373, 11) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2015-01-02 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/broker_summary.parquet (23490538, 16) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2016-01-04 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/insider_activity.parquet (92479, 8) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2017-10-12 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/neo_bdm.parquet (7678, 13) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2026-01-20 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/tradebook_price.parquet (330515, 20) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2026-04-17 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/macro.parquet (4174, 16) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2015-01-01 ┆ 2026-06-05 │
└────────────┴────────────┘
data/raw_canonical/tradebook_time.parquet (1064044, 21) shape: (1, 2)
┌────────────┬────────────┐
│ min        ┆ max        │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2026-04-17 ┆ 2026-06-05 │
└────────────┴────────────┘

In [5]:
import pandas as pd


df = pd.read_excel("data/pure_raw/trading_summary/RingkasanSaham-20260605.xlsx")
df.to_csv("lansa.csv", index=False)

In [ ]:
!ls -lt data/pure_raw/insider_activity/ | head -6

total 256
-rw-r--r--@ 1 albert  staff   3138 Jun  2 22:14 insider_activity_2026-05-28_to_2026-06-02_2026-06-02_22-14-38.csv
-rw-r--r--@ 1 albert  staff  35037 May 28 21:09 insider_activity_2026-05-21_to_2026-05-28_2026-05-28_21-09-47.csv
-rw-r--r--@ 1 albert  staff  29900 May 22 12:19 insider_activity_2026-05-14_to_2026-05-21_2026-05-22_12-19-18.csv
-rw-r--r--@ 1 albert  staff  52754 May 16 10:29 insider_activity_2026-05-04_to_2026-05-14_2026-05-16_10-29-30.csv
-rw-r--r--@ 1 albert  staff    609 May  5 14:38 insider_activity_2026-05-04_to_2026-05-04_2026-05-05_14-38-35.csv

In [4]:
import polars as pl

df = pl.read_parquet("data/features/live/latest/base_features.parquet")

print(df.shape)
print(df.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup"),
    pl.col("has_broksum").fill_null(0).sum().alias("broksum_rows"),
]))

(53676, 198)
shape: (1, 4)
┌────────────┬────────────┬─────┬──────────────┐
│ min_date   ┆ max_date   ┆ dup ┆ broksum_rows │
│ ---        ┆ ---        ┆ --- ┆ ---          │
│ date       ┆ date       ┆ u32 ┆ i64          │
╞════════════╪════════════╪═════╪══════════════╡
│ 2026-02-23 ┆ 2026-05-29 ┆ 0   ┆ 46549        │
└────────────┴────────────┴─────┴──────────────┘

# cek feature parity history vs live

In [1]:
import polars as pl

hist = pl.read_parquet("data/features/history/base_features.parquet")
live = pl.read_parquet("data/features/live/latest/base_features.parquet")

hist_cols = set(hist.columns)
live_cols = set(live.columns)

print("history:", hist.shape)
print("live   :", live.shape)

print("only in history:", sorted(hist_cols - live_cols), len(hist_cols - live_cols))
print("only in live   :", sorted(live_cols - hist_cols), len(live_cols - hist_cols))

print(hist.select([
    pl.col("date").min().alias("hist_min"),
    pl.col("date").max().alias("hist_max"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("hist_dup"),
]))

print(live.select([
    pl.col("date").min().alias("live_min"),
    pl.col("date").max().alias("live_max"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("live_dup"),
]))

history: (1782675, 198)
live   : (39301, 198)
only in history: [] 0
only in live   : [] 0
shape: (1, 3)
┌────────────┬────────────┬──────────┐
│ hist_min   ┆ hist_max   ┆ hist_dup │
│ ---        ┆ ---        ┆ ---      │
│ date       ┆ date       ┆ u32      │
╞════════════╪════════════╪══════════╡
│ 2016-01-04 ┆ 2025-12-30 ┆ 0        │
└────────────┴────────────┴──────────┘
shape: (1, 3)
┌────────────┬────────────┬──────────┐
│ live_min   ┆ live_max   ┆ live_dup │
│ ---        ┆ ---        ┆ ---      │
│ date       ┆ date       ┆ u32      │
╞════════════╪════════════╪══════════╡
│ 2026-03-09 ┆ 2026-05-20 ┆ 0        │
└────────────┴────────────┴──────────┘

In [27]:
import polars as pl

hist = pl.read_parquet("data/features/history/base_features.parquet")
live = pl.read_parquet("data/features/live/latest/base_features.parquet")

hist_cols = set(hist.columns)
live_cols = set(live.columns)

print("history:", hist.shape)
print("live   :", live.shape)

print("only in history:", sorted(hist_cols - live_cols), len(hist_cols - live_cols))
print("only in live   :", sorted(live_cols - hist_cols), len(live_cols - hist_cols))

print(hist.select([
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("hist_dup"),
    pl.col("macro_missing_flag").fill_null(0).sum().alias("hist_macro_missing"),
    pl.col("usd_idr").is_not_null().sum().alias("hist_usd_idr_non_null"),
    pl.col("brent").is_not_null().sum().alias("hist_brent_non_null"),
    pl.col("bi_rate").is_not_null().sum().alias("hist_bi_rate_non_null"),
]))

print(live.select([
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("live_dup"),
    pl.col("macro_missing_flag").fill_null(0).sum().alias("live_macro_missing"),
    pl.col("usd_idr").is_not_null().sum().alias("live_usd_idr_non_null"),
    pl.col("brent").is_not_null().sum().alias("live_brent_non_null"),
    pl.col("bi_rate").is_not_null().sum().alias("live_bi_rate_non_null"),
]))

history: (1782675, 198)
live   : (36424, 198)
only in history: [] 0
only in live   : [] 0
shape: (1, 5)
┌──────────┬────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ hist_dup ┆ hist_macro_missing ┆ hist_usd_idr_non_nul ┆ hist_brent_non_null ┆ hist_bi_rate_non_nu │
│ ---      ┆ ---                ┆ l                    ┆ ---                 ┆ ll                  │
│ u32      ┆ i64                ┆ ---                  ┆ u32                 ┆ ---                 │
│          ┆                    ┆ u32                  ┆                     ┆ u32                 │
╞══════════╪════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 0        ┆ 0                  ┆ 1782675              ┆ 1782675             ┆ 1782675             │
└──────────┴────────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘
shape: (1, 5)
┌──────────┬────────────────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ live_dup ┆ live_macro_missing ┆ live_usd_idr_non_nul ┆ live_brent_non_null ┆ live_bi_rate_non_nu │
│ ---      ┆ ---                ┆ l                    ┆ ---                 ┆ ll                  │
│ u32      ┆ i64                ┆ ---                  ┆ u32                 ┆ ---                 │
│          ┆                    ┆ u32                  ┆                     ┆ u32                 │
╞══════════╪════════════════════╪══════════════════════╪═════════════════════╪═════════════════════╡
│ 0        ┆ 0                  ┆ 36424                ┆ 36424               ┆ 36424               │
└──────────┴────────────────────┴──────────────────────┴─────────────────────┴─────────────────────┘

## Broker Ratio Sanity Check

In [28]:
import polars as pl

df = pl.read_parquet("data/features/history/base_features.parquet")

for c in ["net_flow_ratio", "buyer_dominance_ratio", "seller_dominance_ratio"]:
    print(c)
    print(df.select([
        pl.col(c).is_nan().sum().alias("nan"),
        pl.col(c).is_infinite().sum().alias("inf"),
        pl.col(c).is_null().sum().alias("null"),
        pl.col(c).min().alias("min"),
        pl.col(c).max().alias("max"),
    ]))

net_flow_ratio
shape: (1, 5)
┌─────┬─────┬────────┬───────────┬─────┐
│ nan ┆ inf ┆ null   ┆ min       ┆ max │
│ --- ┆ --- ┆ ---    ┆ ---       ┆ --- │
│ u32 ┆ u32 ┆ u32    ┆ f64       ┆ f64 │
╞═════╪═════╪════════╪═══════════╪═════╡
│ 0   ┆ 0   ┆ 396527 ┆ -0.125568 ┆ 1.0 │
└─────┴─────┴────────┴───────────┴─────┘
buyer_dominance_ratio
shape: (1, 5)
┌─────┬─────┬────────┬──────────┬─────┐
│ nan ┆ inf ┆ null   ┆ min      ┆ max │
│ --- ┆ --- ┆ ---    ┆ ---      ┆ --- │
│ u32 ┆ u32 ┆ u32    ┆ f64      ┆ f64 │
╞═════╪═════╪════════╪══════════╪═════╡
│ 0   ┆ 0   ┆ 396527 ┆ 0.043718 ┆ 1.0 │
└─────┴─────┴────────┴──────────┴─────┘
seller_dominance_ratio
shape: (1, 5)
┌─────┬─────┬────────┬──────────┬─────┐
│ nan ┆ inf ┆ null   ┆ min      ┆ max │
│ --- ┆ --- ┆ ---    ┆ ---      ┆ --- │
│ u32 ┆ u32 ┆ u32    ┆ f64      ┆ f64 │
╞═════╪═════╪════════╪══════════╪═════╡
│ 0   ┆ 0   ┆ 420279 ┆ 0.045119 ┆ 1.0 │
└─────┴─────┴────────┴──────────┴─────┘

# Cek training target distribution

In [31]:
import polars as pl

df = pl.read_parquet("data/datasets/training/full_labeled.parquet")

targets = [
    "label_scalp",
    "label_swing",
    "label_position",
    "label_brok_cont",
    "label_ara_tomorrow",
    "label_silent_accum_breakout",
    "label_big_runner_30d",
]

print(df.shape)

for c in targets:
    print("\n", c, c in df.columns)
    if c in df.columns:
        print(df.group_by(c).len().sort(c))

(1782675, 214)

 label_scalp True
shape: (3, 2)
┌─────────────┬─────────┐
│ label_scalp ┆ len     │
│ ---         ┆ ---     │
│ i8          ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 38219   │
│ 0           ┆ 1430121 │
│ 1           ┆ 314335  │
└─────────────┴─────────┘

 label_swing True
shape: (3, 2)
┌─────────────┬─────────┐
│ label_swing ┆ len     │
│ ---         ┆ ---     │
│ i8          ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 45187   │
│ 0           ┆ 1422488 │
│ 1           ┆ 315000  │
└─────────────┴─────────┘

 label_position True
shape: (3, 2)
┌────────────────┬─────────┐
│ label_position ┆ len     │
│ ---            ┆ ---     │
│ i8             ┆ u32     │
╞════════════════╪═════════╡
│ null           ┆ 54929   │
│ 0              ┆ 1421077 │
│ 1              ┆ 306669  │
└────────────────┴─────────┘

 label_brok_cont True
shape: (3, 2)
┌─────────────────┬─────────┐
│ label_brok_cont ┆ len     │
│ ---             ┆ ---     │
│ i8              ┆ u32     │
╞═════════════════╪═════════╡
│ null            ┆ 982     │
│ 0               ┆ 1378217 │
│ 1               ┆ 403476  │
└─────────────────┴─────────┘

 label_ara_tomorrow True
shape: (3, 2)
┌────────────────────┬─────────┐
│ label_ara_tomorrow ┆ len     │
│ ---                ┆ ---     │
│ i8                 ┆ u32     │
╞════════════════════╪═════════╡
│ null               ┆ 36162   │
│ 0                  ┆ 1709483 │
│ 1                  ┆ 37030   │
└────────────────────┴─────────┘

 label_silent_accum_breakout True
shape: (3, 2)
┌─────────────────────────────┬─────────┐
│ label_silent_accum_breakout ┆ len     │
│ ---                         ┆ ---     │
│ i8                          ┆ u32     │
╞═════════════════════════════╪═════════╡
│ null                        ┆ 84939   │
│ 0                           ┆ 1581892 │
│ 1                           ┆ 115844  │
└─────────────────────────────┴─────────┘

 label_big_runner_30d True
shape: (3, 2)
┌──────────────────────┬─────────┐
│ label_big_runner_30d ┆ len     │
│ ---                  ┆ ---     │
│ i8                   ┆ u32     │
╞══════════════════════╪═════════╡
│ null                 ┆ 64753   │
│ 0                    ┆ 1539159 │
│ 1                    ┆ 178763  │
└──────────────────────┴─────────┘

In [32]:
import polars as pl

df = pl.read_parquet("data/datasets/training/full_labeled.parquet")

targets = [
    "label_scalp",
    "label_swing",
    "label_position",
    "label_brok_cont",
    "label_ara_tomorrow",
    "label_silent_accum_breakout",
    "label_big_runner_30d",
]

print("shape:", df.shape)

for c in targets:
    print("\n" + c)
    print("exists:", c in df.columns)
    if c in df.columns:
        print(df.group_by(c).len().sort(c))
        print(
            df.select(
                (pl.col(c).fill_null(0).sum() / pl.len()).alias("positive_rate")
            )
        )

shape: (1782675, 214)

label_scalp
exists: True
shape: (3, 2)
┌─────────────┬─────────┐
│ label_scalp ┆ len     │
│ ---         ┆ ---     │
│ i8          ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 38219   │
│ 0           ┆ 1430121 │
│ 1           ┆ 314335  │
└─────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.176328      │
└───────────────┘

label_swing
exists: True
shape: (3, 2)
┌─────────────┬─────────┐
│ label_swing ┆ len     │
│ ---         ┆ ---     │
│ i8          ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 45187   │
│ 0           ┆ 1422488 │
│ 1           ┆ 315000  │
└─────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.176701      │
└───────────────┘

label_position
exists: True
shape: (3, 2)
┌────────────────┬─────────┐
│ label_position ┆ len     │
│ ---            ┆ ---     │
│ i8             ┆ u32     │
╞════════════════╪═════════╡
│ null           ┆ 54929   │
│ 0              ┆ 1421077 │
│ 1              ┆ 306669  │
└────────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.172027      │
└───────────────┘

label_brok_cont
exists: True
shape: (3, 2)
┌─────────────────┬─────────┐
│ label_brok_cont ┆ len     │
│ ---             ┆ ---     │
│ i8              ┆ u32     │
╞═════════════════╪═════════╡
│ null            ┆ 982     │
│ 0               ┆ 1378217 │
│ 1               ┆ 403476  │
└─────────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.226332      │
└───────────────┘

label_ara_tomorrow
exists: True
shape: (3, 2)
┌────────────────────┬─────────┐
│ label_ara_tomorrow ┆ len     │
│ ---                ┆ ---     │
│ i8                 ┆ u32     │
╞════════════════════╪═════════╡
│ null               ┆ 36162   │
│ 0                  ┆ 1709483 │
│ 1                  ┆ 37030   │
└────────────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.020772      │
└───────────────┘

label_silent_accum_breakout
exists: True
shape: (3, 2)
┌─────────────────────────────┬─────────┐
│ label_silent_accum_breakout ┆ len     │
│ ---                         ┆ ---     │
│ i8                          ┆ u32     │
╞═════════════════════════════╪═════════╡
│ null                        ┆ 84939   │
│ 0                           ┆ 1581892 │
│ 1                           ┆ 115844  │
└─────────────────────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.064983      │
└───────────────┘

label_big_runner_30d
exists: True
shape: (3, 2)
┌──────────────────────┬─────────┐
│ label_big_runner_30d ┆ len     │
│ ---                  ┆ ---     │
│ i8                   ┆ u32     │
╞══════════════════════╪═════════╡
│ null                 ┆ 64753   │
│ 0                    ┆ 1539159 │
│ 1                    ┆ 178763  │
└──────────────────────┴─────────┘
shape: (1, 1)
┌───────────────┐
│ positive_rate │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.100278      │
└───────────────┘

## Cek target momentum

In [33]:
import polars as pl

df = pl.read_parquet("data/datasets/training/full_labeled.parquet")

targets = [
    "label_momentum_5d",
    "label_momentum_10d",
    "label_momentum_20d",
]

for c in targets:
    print("\n", c, c in df.columns)
    if c in df.columns:
        print(df.group_by(c).len().sort(c))

 label_momentum_5d True
shape: (3, 2)
┌───────────────────┬─────────┐
│ label_momentum_5d ┆ len     │
│ ---               ┆ ---     │
│ i8                ┆ u32     │
╞═══════════════════╪═════════╡
│ null              ┆ 40232   │
│ 0                 ┆ 1423664 │
│ 1                 ┆ 318779  │
└───────────────────┴─────────┘

 label_momentum_10d True
shape: (3, 2)
┌────────────────────┬─────────┐
│ label_momentum_10d ┆ len     │
│ ---                ┆ ---     │
│ i8                 ┆ u32     │
╞════════════════════╪═════════╡
│ null               ┆ 45187   │
│ 0                  ┆ 1418438 │
│ 1                  ┆ 319050  │
└────────────────────┴─────────┘

 label_momentum_20d True
shape: (3, 2)
┌────────────────────┬─────────┐
│ label_momentum_20d ┆ len     │
│ ---                ┆ ---     │
│ i8                 ┆ u32     │
╞════════════════════╪═════════╡
│ null               ┆ 54929   │
│ 0                  ┆ 1410618 │
│ 1                  ┆ 317128  │
└────────────────────┴─────────┘

python3 workflows/train_models.py \
  --root . \
  --fold-set yearly \
  --families multi_strategy_time,sm_tracker,ara_predictor,market_maker_accumulation \
  --algos lgb,xgb,hgb,rank_hgb,regime_hgb

## ?

In [26]:
import polars as pl

hist = pl.read_parquet("data/features/history/base_features.parquet")
live = pl.read_parquet("data/features/live/latest/base_features.parquet")

for name, df in [("history", hist), ("live", live)]:
    print(name, df.shape)
    print(df.select([
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup_ticker_date"),
        pl.col("macro_missing_flag").fill_null(0).sum().alias("macro_missing_rows"),
        pl.col("usd_idr").is_not_null().sum().alias("usd_idr_non_null"),
        pl.col("brent").is_not_null().sum().alias("brent_non_null"),
        pl.col("bi_rate").is_not_null().sum().alias("bi_rate_non_null"),
    ]))

history (1782675, 115)
shape: (1, 5)
┌─────────────────┬────────────────────┬──────────────────┬────────────────┬──────────────────┐
│ dup_ticker_date ┆ macro_missing_rows ┆ usd_idr_non_null ┆ brent_non_null ┆ bi_rate_non_null │
│ ---             ┆ ---                ┆ ---              ┆ ---            ┆ ---              │
│ u32             ┆ i64                ┆ u32              ┆ u32            ┆ u32              │
╞═════════════════╪════════════════════╪══════════════════╪════════════════╪══════════════════╡
│ 0               ┆ 0                  ┆ 1782675          ┆ 1782675        ┆ 1782675          │
└─────────────────┴────────────────────┴──────────────────┴────────────────┴──────────────────┘
live (36424, 145)
shape: (1, 5)
┌─────────────────┬────────────────────┬──────────────────┬────────────────┬──────────────────┐
│ dup_ticker_date ┆ macro_missing_rows ┆ usd_idr_non_null ┆ brent_non_null ┆ bi_rate_non_null │
│ ---             ┆ ---                ┆ ---              ┆ ---            ┆ ---              │
│ u32             ┆ i64                ┆ u32              ┆ u32            ┆ u32              │
╞═════════════════╪════════════════════╪══════════════════╪════════════════╪══════════════════╡
│ 0               ┆ 0                  ┆ 36424            ┆ 36424          ┆ 36424            │
└─────────────────┴────────────────────┴──────────────────┴────────────────┴──────────────────┘

## Check fold n=20

In [2]:
import polars as pl

path = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/datasets/folds/quarterly/fold_19_train.parquet"

df = pl.read_parquet(path)

print(df.shape)
print(df.head())
print(
    df.select([
        pl.col("date").min().alias("min_date"),
        pl.col("date").max().alias("max_date"),
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("duplicate_ticker_date"),
    ])
)

(1642880, 224)
shape: (5, 224)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ rank1_buye ┆ rank1_sel ┆ … ┆ label_mul ┆ label_mom ┆ label_mom ┆ label_mom │
│ ---        ┆ ---    ┆ r          ┆ ler       ┆   ┆ tibagger_ ┆ entum_5d  ┆ entum_10d ┆ entum_20d │
│ date       ┆ str    ┆ ---        ┆ ---       ┆   ┆ 60d       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ i8        ┆ i8        ┆ i8        │
│            ┆        ┆            ┆           ┆   ┆ i8        ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-01-04 ┆ AALI   ┆ DB         ┆ DB        ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0         │
│ 2016-01-04 ┆ ABBA   ┆ LK         ┆ LK        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ABDA   ┆ YU         ┆ YU        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ABMM   ┆ YP         ┆ RF        ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ACES   ┆ DB         ┆ CC        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 3)
┌────────────┬────────────┬───────────────────────┐
│ min_date   ┆ max_date   ┆ duplicate_ticker_date │
│ ---        ┆ ---        ┆ ---                   │
│ date       ┆ date       ┆ u32                   │
╞════════════╪════════════╪═══════════════════════╡
│ 2016-01-04 ┆ 2025-05-27 ┆ 0                     │
└────────────┴────────────┴───────────────────────┘

In [4]:
import polars as pl

path = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/datasets/folds/quarterly/fold_20_train.parquet"

df = pl.read_parquet(path)

print(df.shape)
print(df.head())
print(
    df.select([
        pl.col("date").min().alias("min_date"),
        pl.col("date").max().alias("max_date"),
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("duplicate_ticker_date"),
    ])
)

(1700434, 224)
shape: (5, 224)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ rank1_buye ┆ rank1_sel ┆ … ┆ label_mul ┆ label_mom ┆ label_mom ┆ label_mom │
│ ---        ┆ ---    ┆ r          ┆ ler       ┆   ┆ tibagger_ ┆ entum_5d  ┆ entum_10d ┆ entum_20d │
│ date       ┆ str    ┆ ---        ┆ ---       ┆   ┆ 60d       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ i8        ┆ i8        ┆ i8        │
│            ┆        ┆            ┆           ┆   ┆ i8        ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-01-04 ┆ AALI   ┆ DB         ┆ DB        ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0         │
│ 2016-01-04 ┆ ABBA   ┆ LK         ┆ LK        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ABDA   ┆ YU         ┆ YU        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ABMM   ┆ YP         ┆ RF        ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0         │
│ 2016-01-04 ┆ ACES   ┆ DB         ┆ CC        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 3)
┌────────────┬────────────┬───────────────────────┐
│ min_date   ┆ max_date   ┆ duplicate_ticker_date │
│ ---        ┆ ---        ┆ ---                   │
│ date       ┆ date       ┆ u32                   │
╞════════════╪════════════╪═══════════════════════╡
│ 2016-01-04 ┆ 2025-08-27 ┆ 0                     │
└────────────┴────────────┴───────────────────────┘

# Cek validational signal panel

In [6]:
import polars as pl

p = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/signals/validation/validation_signal_panel.parquet"
df = pl.read_parquet(p)

df

shape: (1_024_737, 35)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ score_sm__ ┆ score_sm_ ┆ … ┆ fwd_ret_5 ┆ fwd_ret_1 ┆ fwd_ret_2 ┆ fwd_ret_3 │
│ ---        ┆ ---    ┆ sm_tracker ┆ _sm_track ┆   ┆ d         ┆ 0d        ┆ 0d        ┆ 0d        │
│ date       ┆ str    ┆ __hgb__bro ┆ er__rank_ ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ …          ┆ hgb…      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆        ┆ ---        ┆ ---       ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ f64        ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2021-01-04 ┆ AALI   ┆ 0.166219   ┆ 0.359086  ┆ … ┆ -0.028681 ┆ -0.110899 ┆ -0.120459 ┆ -0.156788 │
│ 2021-01-04 ┆ ABBA   ┆ 0.311443   ┆ 0.553758  ┆ … ┆ -0.0375   ┆ -0.0125   ┆ -0.2625   ┆ -0.2      │
│ 2021-01-04 ┆ ABDA   ┆ 0.012219   ┆ 0.038113  ┆ … ┆ 0.004484  ┆ 0.040359  ┆ 0.058296  ┆ 0.09417   │
│ 2021-01-04 ┆ ABMM   ┆ 0.1068     ┆ 0.208499  ┆ … ┆ 0.070513  ┆ -0.032051 ┆ -0.089744 ┆ -0.032051 │
│ 2021-01-04 ┆ ACES   ┆ 0.040155   ┆ 0.103714  ┆ … ┆ 0.035294  ┆ 0.032353  ┆ -0.055882 ┆ -0.044118 │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025-12-30 ┆ WOOD   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025-12-30 ┆ WSBP   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025-12-30 ┆ WTON   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025-12-30 ┆ YOII   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2025-12-30 ┆ ZINC   ┆ null       ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [1]:
import polars as pl

p = "signals/validation/sm_tracker_panel.parquet"
df = pl.read_parquet(p)

print(df.shape)
print([c for c in df.columns if c.startswith("score_")])
print(
    df.select([
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup_ticker_date")
    ])
)

(1024340, 19)
['score_sm__sm_tracker__hgb__brok_cont', 'score_sm__sm_tracker__rank_hgb__brok_cont', 'score_sm__sm_tracker__regime_hgb__brok_cont', 'score_sm__sm_tracker__xgb__brok_cont', 'score_sm']
shape: (1, 1)
┌─────────────────┐
│ dup_ticker_date │
│ ---             │
│ u32             │
╞═════════════════╡
│ 0               │
└─────────────────┘

# Check Build live base scores

In [8]:
import json
import polars as pl

df = pl.read_parquet("signals/live/base_scores_2026-05-13.parquet")
policy = json.load(open("configs/signal_policy.json"))

needed = []
for group in ["core_execution", "aggressive_challenger", "watchlist_only"]:
    for s in policy.get(group, []):
        needed.append(s["score_col"])

print("base scores:", df.shape)
print("missing:", [c for c in needed if c not in df.columns])
print([c for c in df.columns if c.startswith("score_")])

base scores: (229, 206)
missing: []
['score_sm', 'score_ara', 'score_mm_silent', 'score_momentum_5d__momentum_ranker__xgb__momentum_5d', 'score_momentum_10d__momentum_ranker__hgb__momentum_10d', 'score_scalp__multi_strategy_time__rank_hgb__scalp', 'score_swing__multi_strategy_time__hgb__swing', 'score_position__multi_strategy_time__xgb__position']

In [5]:
import polars as pl

df = pl.read_parquet("signals/live/base_scores_2026-05-19.parquet")

print(df.shape)
print([c for c in df.columns if c.startswith("score_")])

(252, 206)
['score_sm', 'score_ara', 'score_mm_silent', 'score_momentum_5d__momentum_ranker__xgb__momentum_5d', 'score_momentum_10d__momentum_ranker__hgb__momentum_10d', 'score_scalp__multi_strategy_time__rank_hgb__scalp', 'score_swing__multi_strategy_time__hgb__swing', 'score_position__multi_strategy_time__xgb__position']

# Check hasil build continual feature store

In [7]:
import polars as pl

df = pl.read_parquet("data/features/continual/q3_2024_to_2026_05_20/base_features.parquet")

print(df.shape)
print(df.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup"),
]))

(423912, 198)
shape: (1, 3)
┌────────────┬────────────┬─────┐
│ min_date   ┆ max_date   ┆ dup │
│ ---        ┆ ---        ┆ --- │
│ date       ┆ date       ┆ u32 │
╞════════════╪════════════╪═════╡
│ 2024-07-01 ┆ 2026-05-20 ┆ 0   │
└────────────┴────────────┴─────┘

In [8]:
import polars as pl

df = pl.read_parquet("data/datasets/continual/q3_2024_to_2026_04_30/full_labeled.parquet")

targets = [
    "label_scalp",
    "label_swing",
    "label_position",
    "label_brok_cont",
    "label_ara_tomorrow",
    "label_silent_accum_breakout",
    "label_big_runner_30d",
    "label_momentum_5d",
    "label_momentum_10d",
    "label_momentum_20d",
]

print("shape:", df.shape)

for c in targets:
    print("\n", c, c in df.columns)
    if c in df.columns:
        print(df.group_by(c).len().sort(c))

shape: (416225, 208)

 label_scalp True
shape: (2, 2)
┌─────────────┬────────┐
│ label_scalp ┆ len    │
│ ---         ┆ ---    │
│ i8          ┆ u32    │
╞═════════════╪════════╡
│ 0           ┆ 335279 │
│ 1           ┆ 80946  │
└─────────────┴────────┘

 label_swing True
shape: (3, 2)
┌─────────────┬────────┐
│ label_swing ┆ len    │
│ ---         ┆ ---    │
│ i8          ┆ u32    │
╞═════════════╪════════╡
│ null        ┆ 3896   │
│ 0           ┆ 332119 │
│ 1           ┆ 80210  │
└─────────────┴────────┘

 label_position True
shape: (3, 2)
┌────────────────┬────────┐
│ label_position ┆ len    │
│ ---            ┆ ---    │
│ i8             ┆ u32    │
╞════════════════╪════════╡
│ null           ┆ 18502  │
│ 0              ┆ 319531 │
│ 1              ┆ 78192  │
└────────────────┴────────┘

 label_brok_cont True
shape: (3, 2)
┌─────────────────┬────────┐
│ label_brok_cont ┆ len    │
│ ---             ┆ ---    │
│ i8              ┆ u32    │
╞═════════════════╪════════╡
│ null            ┆ 3896   │
│ 0               ┆ 394160 │
│ 1               ┆ 18169  │
└─────────────────┴────────┘

 label_ara_tomorrow True
shape: (2, 2)
┌────────────────────┬────────┐
│ label_ara_tomorrow ┆ len    │
│ ---                ┆ ---    │
│ i8                 ┆ u32    │
╞════════════════════╪════════╡
│ 0                  ┆ 396340 │
│ 1                  ┆ 19885  │
└────────────────────┴────────┘

 label_silent_accum_breakout True
shape: (3, 2)
┌─────────────────────────────┬────────┐
│ label_silent_accum_breakout ┆ len    │
│ ---                         ┆ ---    │
│ i8                          ┆ u32    │
╞═════════════════════════════╪════════╡
│ null                        ┆ 18502  │
│ 0                           ┆ 375002 │
│ 1                           ┆ 22721  │
└─────────────────────────────┴────────┘

 label_big_runner_30d True
shape: (3, 2)
┌──────────────────────┬────────┐
│ label_big_runner_30d ┆ len    │
│ ---                  ┆ ---    │
│ i8                   ┆ u32    │
╞══════════════════════╪════════╡
│ null                 ┆ 28232  │
│ 0                    ┆ 331210 │
│ 1                    ┆ 56783  │
└──────────────────────┴────────┘

 label_momentum_5d True
shape: (3, 2)
┌───────────────────┬────────┐
│ label_momentum_5d ┆ len    │
│ ---               ┆ ---    │
│ i8                ┆ u32    │
╞═══════════════════╪════════╡
│ null              ┆ 3896   │
│ 0                 ┆ 332119 │
│ 1                 ┆ 80210  │
└───────────────────┴────────┘

 label_momentum_10d True
shape: (3, 2)
┌────────────────────┬────────┐
│ label_momentum_10d ┆ len    │
│ ---                ┆ ---    │
│ i8                 ┆ u32    │
╞════════════════════╪════════╡
│ null               ┆ 8766   │
│ 0                  ┆ 328210 │
│ 1                  ┆ 79249  │
└────────────────────┴────────┘

 label_momentum_20d True
shape: (3, 2)
┌────────────────────┬────────┐
│ label_momentum_20d ┆ len    │
│ ---                ┆ ---    │
│ i8                 ┆ u32    │
╞════════════════════╪════════╡
│ null               ┆ 18502  │
│ 0                  ┆ 319531 │
│ 1                  ┆ 78192  │
└────────────────────┴────────┘

## cek panel signal

In [1]:
import polars as pl

p = "signals/validation/continual_q3_2024_q1_2026_panel.parquet"
df = pl.read_parquet(p)

print(df.shape)
print([c for c in df.columns if c.startswith("score_")])
print(df.select([
    pl.col("date").min().alias("min_date"),
    pl.col("date").max().alias("max_date"),
    pl.struct(["date", "ticker"]).is_duplicated().sum().alias("dup_ticker_date"),
]))

df

(298682, 49)
['score_ara__ara_predictor__hgb__ara_tomorrow', 'score_ara__ara_predictor__rank_hgb__ara_tomorrow', 'score_ara__ara_predictor__regime_hgb__ara_tomorrow', 'score_ara__ara_predictor__xgb__ara_tomorrow', 'score_momentum_10d__momentum_ranker__hgb__momentum_10d', 'score_momentum_20d__momentum_ranker__hgb__momentum_20d', 'score_momentum_5d__momentum_ranker__hgb__momentum_5d', 'score_momentum_10d__momentum_ranker__rank_hgb__momentum_10d', 'score_momentum_20d__momentum_ranker__rank_hgb__momentum_20d', 'score_momentum_5d__momentum_ranker__rank_hgb__momentum_5d', 'score_momentum_10d__momentum_ranker__regime_hgb__momentum_10d', 'score_momentum_20d__momentum_ranker__regime_hgb__momentum_20d', 'score_momentum_5d__momentum_ranker__regime_hgb__momentum_5d', 'score_momentum_10d__momentum_ranker__xgb__momentum_10d', 'score_momentum_20d__momentum_ranker__xgb__momentum_20d', 'score_momentum_5d__momentum_ranker__xgb__momentum_5d', 'score_position__multi_strategy_time__hgb__position', 'score_scalp__multi_strategy_time__hgb__scalp', 'score_swing__multi_strategy_time__hgb__swing', 'score_position__multi_strategy_time__rank_hgb__position', 'score_scalp__multi_strategy_time__rank_hgb__scalp', 'score_swing__multi_strategy_time__rank_hgb__swing', 'score_position__multi_strategy_time__regime_hgb__position', 'score_scalp__multi_strategy_time__regime_hgb__scalp', 'score_swing__multi_strategy_time__regime_hgb__swing', 'score_position__multi_strategy_time__xgb__position', 'score_scalp__multi_strategy_time__xgb__scalp', 'score_swing__multi_strategy_time__xgb__swing', 'score_ara', 'score_momentum_10d', 'score_momentum_20d', 'score_momentum_5d', 'score_position', 'score_scalp', 'score_swing']
shape: (1, 3)
┌────────────┬────────────┬─────────────────┐
│ min_date   ┆ max_date   ┆ dup_ticker_date │
│ ---        ┆ ---        ┆ ---             │
│ date       ┆ date       ┆ u32             │
╞════════════╪════════════╪═════════════════╡
│ 2025-01-02 ┆ 2026-04-29 ┆ 0               │
└────────────┴────────────┴─────────────────┘

shape: (298_682, 49)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date       ┆ ticker ┆ score_ara_ ┆ score_ara ┆ … ┆ fwd_ret_5 ┆ fwd_ret_1 ┆ fwd_ret_2 ┆ fwd_ret_3 │
│ ---        ┆ ---    ┆ _ara_predi ┆ __ara_pre ┆   ┆ d         ┆ 0d        ┆ 0d        ┆ 0d        │
│ date       ┆ str    ┆ ctor__hgb_ ┆ dictor__r ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ …          ┆ ank…      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆        ┆ ---        ┆ ---       ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆ f64        ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2025-01-02 ┆ AADI   ┆ 0.002102   ┆ 0.00382   ┆ … ┆ -0.06383  ┆ 0.069909  ┆ 0.075988  ┆ -0.018237 │
│ 2025-01-02 ┆ AALI   ┆ 0.011286   ┆ 0.007279  ┆ … ┆ -0.028455 ┆ -0.028455 ┆ -0.060976 ┆ -0.036585 │
│ 2025-01-02 ┆ ABBA   ┆ 0.031312   ┆ 0.043778  ┆ … ┆ 0.0       ┆ 0.037037  ┆ -0.296296 ┆ -0.259259 │
│ 2025-01-02 ┆ ABDA   ┆ 0.011408   ┆ 0.009523  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 2025-01-02 ┆ ABMM   ┆ 0.001596   ┆ 0.004338  ┆ … ┆ -0.036415 ┆ -0.019608 ┆ -0.053221 ┆ -0.047619 │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-04-29 ┆ ZATA   ┆ 0.049058   ┆ 0.049745  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-04-29 ┆ ZBRA   ┆ 0.001188   ┆ 0.001949  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-04-29 ┆ ZINC   ┆ 0.001186   ┆ 0.001953  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-04-29 ┆ ZONE   ┆ 0.082606   ┆ 0.140979  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2026-04-29 ┆ ZYRX   ┆ 0.01311    ┆ 0.012163  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# BI RATE Scraper

In [22]:
# CONFIG
api_key = "cdc65504d0b176f0b763f2d8dcd855dd"

import requests
import time
import json
import os
import random

api_key = ""

years = {
    2026: 126,
    2025: 125,
    2024: 124,
    2023: 123,
    2022: 122,
    2021: 121,
    2020: 120,
    2019: 119,
    2018: 118,
    2017: 117,
    2016: 116,
    2015: 115,
}

base_url = "https://webapi.bps.go.id/v1/api/list/model/data/lang/eng/domain/0000/var/379/th/{th}/key/{key}"

output_dir = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate"
os.makedirs(output_dir, exist_ok=True)

log_file = os.path.join(output_dir, "download_log.txt")

# FUNCTION: FETCH WITH RETRY
def fetch_bps(th, api_key, max_retry=3):
    url = base_url.format(th=th, key=api_key)
    for attempt in range(1, max_retry + 1):
        try:
            r = requests.get(url, timeout=30)
            # sukses
            if r.status_code == 200:
                return r.json()
            print(f"HTTP {r.status_code} (attempt {attempt})")
        except Exception as e:
            print(f"Exception (attempt {attempt}): {e}")
        # exponential backoff
        sleep_time = (2 ** attempt) + random.random()
        print(f"RETRY in {sleep_time:.2f}s")
        time.sleep(sleep_time)
    raise Exception(f"Failed after {max_retry} retries for th={th}")

# MAIN LOOP
for year, th in years.items():
    file_path = os.path.join(output_dir, f"bi_rate_{year}.json")
    # RESUME LOGIC (skip jika sudah ada)
    if os.path.exists(file_path):
        print(f"SKIP {year} (already exists)")
        continue
    print(f"\n FETCHING {year}...")
    try:
        data = fetch_bps(th, api_key)
        # validasi status API
        if data.get("status") != "OK":
            print(f"!!! {year} status NOT OK")
            continue
        # simpan file
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"SAVED {file_path}")
        # log success
        with open(log_file, "a") as log:
            log.write(f"SUCCESS {year}\n")
    except Exception as e:
        print(f"FAILED {year}: {e}")
        # log failure
        with open(log_file, "a") as log:
            log.write(f"FAILED {year}: {e}\n")

    # SAFE DELAY (anti overload)
    sleep_time = 1.5 + random.random()
    print(f"SLEEP {sleep_time:.2f}s\n")
    time.sleep(sleep_time)

print("\nDONE - All available data processed")

<>:83: SyntaxWarning: invalid escape sequence '\D'
<>:83: SyntaxWarning: invalid escape sequence '\D'
/var/folders/pt/n4kz04ns6wn8sv6msgx6mqb80000gn/T/ipykernel_7933/3722219837.py:83: SyntaxWarning: invalid escape sequence '\D'
  print("\DONE - All available data processed")

 FETCHING 2026...
HTTP 500 (attempt 1)
⏳ retry in 2.94s
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2026.json
💤 sleep 2.48s


 FETCHING 2025...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2025.json
💤 sleep 1.93s


 FETCHING 2024...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2024.json
💤 sleep 2.23s


 FETCHING 2023...
HTTP 500 (attempt 1)
⏳ retry in 2.90s
HTTP 500 (attempt 2)
⏳ retry in 4.88s
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2023.json
💤 sleep 1.78s


 FETCHING 2022...
HTTP 500 (attempt 1)
⏳ retry in 2.28s
HTTP 500 (attempt 2)
⏳ retry in 4.53s
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2022.json
💤 sleep 2.49s


 FETCHING 2021...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2021.json
💤 sleep 2.18s


 FETCHING 2020...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2020.json
💤 sleep 2.37s


 FETCHING 2019...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2019.json
💤 sleep 2.21s


 FETCHING 2018...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2018.json
💤 sleep 1.71s


 FETCHING 2017...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2017.json
💤 sleep 1.66s


 FETCHING 2016...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2016.json
💤 sleep 2.36s


 FETCHING 2015...
SAVED /Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/bps_bi_rate/bi_rate_2015.json
💤 sleep 1.65s

\DONE - All available data processed

In [ ]:
# python3 workflows/build_macro.py \
#   --root . \
#   --start-date 2015-01-01 \
#   --end-date 2026-05-13 \
#   --mode scrape \
#   --force \
#   --download-bi-rate \
#   --bps-api-key "cdc65504d0b176f0b763f2d8dcd855dd"

# python3 workflows/build_canonical_raw.py \
#   --root . \
#   --start-date 2015-01-01 \
#   --end-date 2026-05-13 \
#   --macro-mode scrape \
#   --force-macro \
#   --download-bi-rate \
#   --bps-api-key "cdc65504d0b176f0b763f2d8dcd855dd"

# Feature coverage QA

In [10]:
import polars as pl

df = pl.read_parquet("data/features/history/base_features.parquet")

cols = [
    "has_broksum",
    "buy_val_total_sane",
    "net_flow_ratio",
    "rank1_same_buyer_streak",
    "rank1_buyer_daily_share",
    "has_insider_activity",
    "has_corporate_action",
    "macro_missing_flag",
    "has_bdm_any",
]

for c in cols:
    if c in df.columns:
        print("\n", c)
        print(
            df.select([
                pl.len().alias("rows"),
                pl.col(c).is_not_null().sum().alias("non_null"),
                pl.col(c).fill_null(0).sum().alias("sum_or_count"),
            ])
        )
    else:
        print("MISSING:", c)

 has_broksum
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 1386175      │
└─────────┴──────────┴──────────────┘

 buy_val_total_sane
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ f64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1329367  ┆ 2.1043e16    │
└─────────┴──────────┴──────────────┘

 net_flow_ratio
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ f64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1360424  ┆ NaN          │
└─────────┴──────────┴──────────────┘

 rank1_same_buyer_streak
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 2927650      │
└─────────┴──────────┴──────────────┘

 rank1_buyer_daily_share
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ f64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1386175  ┆ 95414.435545 │
└─────────┴──────────┴──────────────┘

 has_insider_activity
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 58633        │
└─────────┴──────────┴──────────────┘

 has_corporate_action
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 601          │
└─────────┴──────────┴──────────────┘

 macro_missing_flag
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 1782675      │
└─────────┴──────────┴──────────────┘

 has_bdm_any
shape: (1, 3)
┌─────────┬──────────┬──────────────┐
│ rows    ┆ non_null ┆ sum_or_count │
│ ---     ┆ ---      ┆ ---          │
│ u32     ┆ u32      ┆ i64          │
╞═════════╪══════════╪══════════════╡
│ 1782675 ┆ 1782675  ┆ 0            │
└─────────┴──────────┴──────────────┘

In [12]:
import polars as pl

paths = [
    "data/features/history/base_features.parquet",
    "data/features/live/latest/base_features.parquet",
]

for p in paths:
    df = pl.read_parquet(p)
    numeric_cols = [
        c for c, d in zip(df.columns, df.dtypes)
        if d in (pl.Float32, pl.Float64)
    ]

    df = df.with_columns([
        pl.when(pl.col(c).is_nan() | pl.col(c).is_infinite())
          .then(None)
          .otherwise(pl.col(c))
          .alias(c)
        for c in numeric_cols
    ])

    df.write_parquet(p)
    print("cleaned", p, df.shape)

cleaned data/features/history/base_features.parquet (1782675, 138)
cleaned data/features/live/latest/base_features.parquet (39301, 138)

In [13]:
import polars as pl

df = pl.read_parquet("data/features/history/base_features.parquet")

for c in ["net_flow_ratio", "buyer_dominance_ratio", "seller_dominance_ratio"]:
    if c in df.columns:
        print(c)
        print(df.select([
            pl.col(c).is_nan().sum().alias("nan"),
            pl.col(c).is_infinite().sum().alias("inf"),
            pl.col(c).is_null().sum().alias("null"),
            pl.col(c).min().alias("min"),
            pl.col(c).max().alias("max"),
        ]))

net_flow_ratio
shape: (1, 5)
┌─────┬─────┬────────┬────────────────┬──────────┐
│ nan ┆ inf ┆ null   ┆ min            ┆ max      │
│ --- ┆ --- ┆ ---    ┆ ---            ┆ ---      │
│ u32 ┆ u32 ┆ u32    ┆ f64            ┆ f64      │
╞═════╪═════╪════════╪════════════════╪══════════╡
│ 0   ┆ 0   ┆ 426330 ┆ -145085.894059 ┆ 6.0189e6 │
└─────┴─────┴────────┴────────────────┴──────────┘
buyer_dominance_ratio
shape: (1, 5)
┌─────┬─────┬────────┬──────────┬─────┐
│ nan ┆ inf ┆ null   ┆ min      ┆ max │
│ --- ┆ --- ┆ ---    ┆ ---      ┆ --- │
│ u32 ┆ u32 ┆ u32    ┆ f64      ┆ f64 │
╞═════╪═════╪════════╪══════════╪═════╡
│ 0   ┆ 0   ┆ 396500 ┆ 0.043718 ┆ 1.0 │
└─────┴─────┴────────┴──────────┴─────┘
seller_dominance_ratio
shape: (1, 5)
┌─────┬─────┬────────┬──────────┬─────┐
│ nan ┆ inf ┆ null   ┆ min      ┆ max │
│ --- ┆ --- ┆ ---    ┆ ---      ┆ --- │
│ u32 ┆ u32 ┆ u32    ┆ f64      ┆ f64 │
╞═════╪═════╪════════╪══════════╪═════╡
│ 0   ┆ 0   ┆ 420253 ┆ 0.045119 ┆ 1.0 │
└─────┴─────┴────────┴──────────┴─────┘

untuk OHLCV, actual coverage dari date=2015-01-02.

date,ticker,open,high,low,close,volume
2015-01-02,AALI,16715.333882176663,17196.84584211245,16680.940170752678,16904.5,1385945.0
2015-01-02,ABMM,2110.177001953125,2110.177001953125,2110.177001953125,2110.177001953125,0.0
ETC.


Broker Summary, actual coverage dari date=2016-01-04

stock_code,date,from,to,rank,BY,BY_type,B.val,B.lot,B.freq,B.avg,SL,SL_type,S.val,S.lot,S.freq,S.avg
AALI,20160104,2016-01-04,2016-01-04,1,DB,,6.55022e+09,4105,53,15956.686967113277,DB,,1.123298e+10,7086,449,15852.356759808072
AALI,20160104,2016-01-04,2016-01-04,2,FG,,4.4667825e+09,2846,287,15694.949051300071,NI,Pemerintah,1.259055e+09,801,87,15718.539325842698
ETC.


insider activity, actual coverage=12 Oct 17
8823,12 Oct 17,ASJT,DANA PENSIUN PERKEBUNAN,SELL,"1,200",0.00,"464,453,200",77.41,"464,452,000",77.41,0,,UNSPECIFIED,LOCAL,KSEI,Sumber: KSEI
8809,12 Oct 17,ACES,SMALLCAP WORLD FUND,BUY,"4,646,900",+0.03,"874,736,465",5.10,"879,383,365",5.13,0,,UNSPECIFIED,FOREIGN,KSEI,Sumber: KSEI

corporate action, actual coverage date=22 May 1979
20 Dec 1979,BATI,IPO,6600000,6600000
22 May 1979,CNTX,IPO,116000,116000

macro, expected coverage since 2015-01-02 and load IDR/UIDRTOUSD, COAL, BRENT, Etc.

neo bdm, actual coverage date=28_jan_2026
├── 28_jan_2026_neobdm-f-d.csv
├── 28_jan_2026_neobdm-f-w.csv
├── 28_jan_2026_neobdm-m-d.csv
├── 28_jan_2026_neobdm-m-w.csv
├── 28_jan_2026_neobdm-nr-d.csv
├── 28_jan_2026_neobdm-nr-w.csv


tradebook/orderbook, actual coverage date=2026-05-07
├── orderbook_levels_2026-05-04_21-42-12.csv
├── orderbook_snapshot_2026-05-04_21-42-12.csv
├── tradebook_price_2026-04-19_11-04-14.csv
├── tradebook_time_2026-04-19_11-04-14.csv

ketika saya menjalankan takap ke-2 yakni build feature store, ada masalah yang yang terjadi. Dimana historicall build berhasil[2.1] dieksekusi namun live feature tidak [2.2], anda bisa melakukan diagnosa serta melakukan analisa dan audit mendalam setelah melihat log dan reporr berikut:
2.1 build historical feature store
python3 workflows/build_feature_store.py \
  --root . \
  --scope history \
  --start-date 2016-01-01 \
  --end-date 2025-12-31
{
  "scope": "history", "start_date": "2016-01-01", "end_date": "2025-12-31", "rows": 1782675, "cols": 34,
  "path": "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/features/history/base_features.parquet",
  "feature_count": 32,
  "feature_cols": ["open", "high", "low", "close", "volume", "value", "frequency", "foreign_buy", "foreign_sell", "ret_1d", "ret_5d", "ret_10d", "ret_20d", "ma_5", "ma_20", "volume_ma20", "volatility_20d", "close_vs_ma20", "volume_ratio_20d", "traded_value_proxy", "insider_event_count", "insider_buy_count", "insider_sell_count", "insider_net_shares", "insider_net_pct_sum", "has_insider_activity", "has_broksum", "has_bdm_any", "cs_rank_ret_5d", "cs_rank_ret_10d", "cs_rank_ret_20d", "cs_rank_volume_ratio_20d"
  ]
}

saya juga mengecek base_features yang dihasilkan, berikut adalah hasilny:
(1782675, 34)
shape: (5, 34)

 date        ticker  open        high       …  cs_rank_r  cs_rank_r  cs_rank_r  cs_rank_v 
 ---         ---     ---         ---           et_5d      et_10d     et_20d     olume_rat 
 date        str     f64         f64           ---        ---        ---        io_20d    
                                               f64        f64        f64        ---       
                                                                                f64       

 2016-01-04  AALI    11127.7366  11197.943  …  null       null       null       null      
                     29          211                                                      
 2016-01-04  ABBA    39.726902   39.726902  …  null       null       null       null      
 2016-01-04  ABDA    6746.96679  6746.9667  …  null       null       null       null      
                     7           97                                                       
 2016-01-04  ABMM    1868.02568  1868.0256  …  null       null       null       null      
                     5           85                                                       
 2016-01-04  ACES    605.644027  616.92932  …  null       null       null       null      

shape: (1, 3)

 min_date    max_date    duplicate_ticker_date 
 ---         ---         ---                   
 date        date        u32                   

 2016-01-04  2025-12-30  0                     



2.2 build live feature store
python3 workflows/build_feature_store.py \
  --root . \
  --scope live \
  --start-date 2026-03-09 \
  --end-date 2026-05-13
Traceback (most recent call last):
  File "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/workflows/build_feature_store.py", line 12, in <module>
    if __name__=="__main__": main()
                             ^^^^^^
  File "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/workflows/build_feature_store.py", line 11, in main
    m=build_feature_store(root,a.start_date,a.end_date,a.scope,out); print(json.dumps(m,indent=2,default=str))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/src/alpha_research/features/store.py", line 209, in build_feature_store
    base=add_price_features(load_ohlcv(raw_dir,start,end))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/src/alpha_research/features/store.py", line 39, in load_ohlcv
    raise ValueError(
ValueError: No OHLCV rows remain after date filtering. start=2026-09-03, end=2026-05-13, files_read=10, path=/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/raw/ohlcv. For historical feature store, make sure historical OHLCV files exist in data/raw/ohlcv, not only daily pure_raw trading summary files.

In [ ]:
import polars as pl

path = "/Users/albert/Documents/Finances/projects/02_alpha_research/alpha_research/data/news/event_intelligence/report/event_study_by_event_type.csv"

df = pl.read_parquet(path)

print(df.shape)
print(df.head())
print(
    df.select([
        pl.col("date").min().alias("min_date"),
        pl.col("date").max().alias("max_date"),
        pl.struct(["date", "ticker"]).is_duplicated().sum().alias("duplicate_ticker_date"),
    ])
)

(1995448, 11)
shape: (5, 11)
┌────────────┬────────┬─────────────┬────────────┬───┬───────┬───────────┬────────────┬────────────┐
│ date       ┆ ticker ┆ open        ┆ high       ┆ … ┆ value ┆ frequency ┆ foreign_bu ┆ foreign_se │
│ ---        ┆ ---    ┆ ---         ┆ ---        ┆   ┆ ---   ┆ ---       ┆ y          ┆ ll         │
│ date       ┆ str    ┆ f64         ┆ f64        ┆   ┆ f64   ┆ f64       ┆ ---        ┆ ---        │
│            ┆        ┆             ┆            ┆   ┆       ┆           ┆ f64        ┆ f64        │
╞════════════╪════════╪═════════════╪════════════╪═══╪═══════╪═══════════╪════════════╪════════════╡
│ 2015-01-02 ┆ AALI   ┆ 16715.33388 ┆ 17196.8458 ┆ … ┆ null  ┆ null      ┆ null       ┆ null       │
│            ┆        ┆ 2           ┆ 42         ┆   ┆       ┆           ┆            ┆            │
│ 2015-01-02 ┆ ABBA   ┆ 48.46682    ┆ 50.055897  ┆ … ┆ null  ┆ null      ┆ null       ┆ null       │
│ 2015-01-02 ┆ ABDA   ┆ 5533.175293 ┆ 5533.17529 ┆ … ┆ null  ┆ null      ┆ null       ┆ null       │
│            ┆        ┆             ┆ 3          ┆   ┆       ┆           ┆            ┆            │
│ 2015-01-02 ┆ ABMM   ┆ 2110.177002 ┆ 2110.17700 ┆ … ┆ null  ┆ null      ┆ null       ┆ null       │
│            ┆        ┆             ┆ 2          ┆   ┆       ┆           ┆            ┆            │
│ 2015-01-02 ┆ ACES   ┆ 576.700535  ┆ 580.373786 ┆ … ┆ null  ┆ null      ┆ null       ┆ null       │
└────────────┴────────┴─────────────┴────────────┴───┴───────┴───────────┴────────────┴────────────┘
shape: (1, 3)
┌────────────┬────────────┬───────────────────────┐
│ min_date   ┆ max_date   ┆ duplicate_ticker_date │
│ ---        ┆ ---        ┆ ---                   │
│ date       ┆ date       ┆ u32                   │
╞════════════╪════════════╪═══════════════════════╡
│ 2015-01-02 ┆ 2026-05-20 ┆ 0                     │
└────────────┴────────────┴───────────────────────┘

# Audit sample event type

In [1]:
import polars as pl

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

(
    df.filter(pl.col("event_type") == "suspension_uma")
      .select(["news_date", "source", "title", "ticker", "event_type", "event_side"])
      .head(30)
      .write_csv("data/news/event_intelligence/audit_suspension_uma_sample.csv")
)

## Buat QA report

In [2]:
import polars as pl

path = "data/news/event_intelligence/news_event_intelligence_dataset.parquet"
df = pl.read_parquet(path)

print("shape:", df.shape)

print("\nDate range:")
print(df.select([
    pl.col("news_date").min().alias("min_date"),
    pl.col("news_date").max().alias("max_date"),
]))

print("\nRows by year:")
print(
    df.with_columns(pl.col("news_date").dt.year().alias("year"))
      .group_by("year")
      .len()
      .sort("year")
)

print("\nSource distribution:")
print(df.group_by("source").len().sort("len", descending=True))

print("\nEvent type distribution:")
print(df.group_by("event_type").len().sort("len", descending=True))

print("\nEvent type by source:")
print(
    df.group_by(["source", "event_type"])
      .len()
      .sort("len", descending=True)
      .head(50)
)

print("\nOutcome completeness:")
outcome_cols = [
    "fwd_ret_5d",
    "market_alpha_5d",
    "sector_alpha_5d",
    "volatility_shock_5d",
    "mae_5d",
    "mfe_5d",
    "reaction_label_5d",
]
print(
    df.select([
        pl.col(c).is_null().mean().alias(f"{c}_null_rate")
        for c in outcome_cols
        if c in df.columns
    ])
)

print("\nDuplicate event_row_id:")
print(df.select(pl.col("event_row_id").n_unique().alias("unique_event_row_id")))
print("rows:", df.height)

shape: (127123, 122)

Date range:
shape: (1, 2)
┌────────────┬────────────┐
│ min_date   ┆ max_date   │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2020-01-02 ┆ 2026-05-23 │
└────────────┴────────────┘

Rows by year:
shape: (7, 2)
┌──────┬───────┐
│ year ┆ len   │
│ ---  ┆ ---   │
│ i32  ┆ u32   │
╞══════╪═══════╡
│ 2020 ┆ 2760  │
│ 2021 ┆ 14425 │
│ 2022 ┆ 20850 │
│ 2023 ┆ 18090 │
│ 2024 ┆ 25352 │
│ 2025 ┆ 26783 │
│ 2026 ┆ 18863 │
└──────┴───────┘

Source distribution:
shape: (3, 2)
┌─────────────┬───────┐
│ source      ┆ len   │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ IDX Channel ┆ 93472 │
│ unknown     ┆ 32939 │
│ Kabar Bursa ┆ 712   │
└─────────────┴───────┘

Event type distribution:
shape: (17, 2)
┌──────────────────────┬───────┐
│ event_type           ┆ len   │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ suspension_uma       ┆ 52386 │
│ market_commentary    ┆ 15785 │
│ earnings_fundamental ┆ 13805 │
│ accumulation_flow    ┆ 10127 │
│ dividend             ┆ 6520  │
│ …                    ┆ …     │
│ general_news         ┆ 1083  │
│ macro_currency       ┆ 820   │
│ macro_rate           ┆ 705   │
│ geopolitical_risk    ┆ 255   │
│ index_rebalancing    ┆ 135   │
└──────────────────────┴───────┘

Event type by source:
shape: (47, 3)
┌─────────────┬───────────────────────────┬───────┐
│ source      ┆ event_type                ┆ len   │
│ ---         ┆ ---                       ┆ ---   │
│ str         ┆ str                       ┆ u32   │
╞═════════════╪═══════════════════════════╪═══════╡
│ IDX Channel ┆ suspension_uma            ┆ 35607 │
│ unknown     ┆ suspension_uma            ┆ 16537 │
│ IDX Channel ┆ market_commentary         ┆ 15313 │
│ IDX Channel ┆ earnings_fundamental      ┆ 10089 │
│ IDX Channel ┆ accumulation_flow         ┆ 6139  │
│ …           ┆ …                         ┆ …     │
│ unknown     ┆ index_rebalancing         ┆ 16    │
│ Kabar Bursa ┆ business_development      ┆ 11    │
│ Kabar Bursa ┆ commodity_shock           ┆ 9     │
│ Kabar Bursa ┆ buyback                   ┆ 5     │
│ Kabar Bursa ┆ dilution_corporate_action ┆ 2     │
└─────────────┴───────────────────────────┴───────┘

Outcome completeness:
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ fwd_ret_5d_n ┆ market_alph ┆ sector_alph ┆ volatility_ ┆ mae_5d_null ┆ mfe_5d_null ┆ reaction_la │
│ ull_rate     ┆ a_5d_null_r ┆ a_5d_null_r ┆ shock_5d_nu ┆ _rate       ┆ _rate       ┆ bel_5d_null │
│ ---          ┆ ate         ┆ ate         ┆ ll_rate     ┆ ---         ┆ ---         ┆ _rate       │
│ f64          ┆ ---         ┆ ---         ┆ ---         ┆ f64         ┆ f64         ┆ ---         │
│              ┆ f64         ┆ f64         ┆ f64         ┆             ┆             ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.0198       ┆ 0.0198      ┆ 0.0198      ┆ 0.054758    ┆ 0.010281    ┆ 0.010281    ┆ 0.0         │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

Duplicate event_row_id:
shape: (1, 1)
┌─────────────────────┐
│ unique_event_row_id │
│ ---                 │
│ u32                 │
╞═════════════════════╡
│ 127123              │
└─────────────────────┘
rows: 127123

In [4]:
import polars as pl

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

print("shape:", df.shape)

print("\nDate range:")
print(df.select([
    pl.col("news_date").min().alias("min_date"),
    pl.col("news_date").max().alias("max_date"),
]))

print("\nEvent type distribution:")
print(
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
)

print("\nMacro currency sample titles:")
print(
    df.filter(pl.col("event_type") == "macro_currency")
      .select(["news_date", "title", "ticker", "event_type", "event_side"])
      .head(50)
)

shape: (127123, 122)

Date range:
shape: (1, 2)
┌────────────┬────────────┐
│ min_date   ┆ max_date   │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 2020-01-02 ┆ 2026-05-23 │
└────────────┴────────────┘

Event type distribution:
shape: (21, 2)
┌───────────────────────────┬───────┐
│ event_type                ┆ len   │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ market_commentary         ┆ 32108 │
│ earnings_fundamental      ┆ 26333 │
│ business_development      ┆ 10352 │
│ dividend                  ┆ 8810  │
│ dilution_corporate_action ┆ 7551  │
│ …                         ┆ …     │
│ macro_rate                ┆ 1383  │
│ debt_financing            ┆ 1291  │
│ macro_currency            ┆ 1033  │
│ credit_rating             ┆ 726   │
│ stock_split               ┆ 551   │
└───────────────────────────┴───────┘

Macro currency sample titles:
shape: (50, 5)
┌────────────┬─────────────────────────────────┬────────┬────────────────┬──────────────────┐
│ news_date  ┆ title                           ┆ ticker ┆ event_type     ┆ event_side       │
│ ---        ┆ ---                             ┆ ---    ┆ ---            ┆ ---              │
│ date       ┆ str                             ┆ str    ┆ str            ┆ str              │
╞════════════╪═════════════════════════════════╪════════╪════════════════╪══════════════════╡
│ 2021-05-06 ┆ MNC Sekuritas Gelar TRAKTOR, B… ┆ BCAP   ┆ macro_currency ┆ sector_dependent │
│ 2021-05-31 ┆ Rupiah Ditutup Tertekan ke Rp1… ┆ EURO   ┆ macro_currency ┆ sector_dependent │
│ 2021-07-23 ┆ Ini Ramalan OCBC NISP untuk Ha… ┆ NISP   ┆ macro_currency ┆ sector_dependent │
│ 2021-10-18 ┆ HUT ke-32, Yuk Ikut "Nyapit Cu… ┆ BCAP   ┆ macro_currency ┆ sector_dependent │
│ 2022-01-25 ┆ Jelang Pertemuan The Fed, Rupi… ┆ NATO   ┆ macro_currency ┆ sector_dependent │
│ …          ┆ …                               ┆ …      ┆ …              ┆ …                │
│ 2022-10-27 ┆ IHSG Berpotensi Koreksi Wajar … ┆ AALI   ┆ macro_currency ┆ sector_dependent │
│ 2022-10-27 ┆ IHSG Berpotensi Koreksi Wajar … ┆ GGRM   ┆ macro_currency ┆ sector_dependent │
│ 2022-10-27 ┆ IHSG Berpotensi Koreksi Wajar … ┆ AKRA   ┆ macro_currency ┆ sector_dependent │
│ 2022-12-26 ┆ Salip Kekayaan Keluarga Harton… ┆ BYAN   ┆ macro_currency ┆ sector_dependent │
│ 2023-04-05 ┆ Dolar AS Masih Jadi Mata Uang … ┆ CHIP   ┆ macro_currency ┆ sector_dependent │
└────────────┴─────────────────────────────────┴────────┴────────────────┴──────────────────┘

### Re-chek distribusi event type

In [6]:
import polars as pl

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

print(
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
)

shape: (17, 2)
┌──────────────────────┬───────┐
│ event_type           ┆ len   │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ earnings_fundamental ┆ 24319 │
│ market_commentary    ┆ 20979 │
│ accumulation_flow    ┆ 16589 │
│ dividend             ┆ 10846 │
│ distribution_flow    ┆ 9485  │
│ …                    ┆ …     │
│ general_news         ┆ 1735  │
│ macro_currency       ┆ 1269  │
│ macro_rate           ┆ 1093  │
│ geopolitical_risk    ┆ 430   │
│ index_rebalancing    ┆ 226   │
└──────────────────────┴───────┘

In [1]:
import polars as pl

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

print(
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
)

shape: (21, 2)
┌───────────────────────────┬───────┐
│ event_type                ┆ len   │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ market_commentary         ┆ 32189 │
│ earnings_fundamental      ┆ 24985 │
│ business_development      ┆ 11060 │
│ dividend                  ┆ 8810  │
│ dilution_corporate_action ┆ 7551  │
│ …                         ┆ …     │
│ macro_currency            ┆ 1524  │
│ macro_rate                ┆ 1361  │
│ debt_financing            ┆ 1291  │
│ credit_rating             ┆ 726   │
│ stock_split               ┆ 551   │
└───────────────────────────┴───────┘

In [3]:
import polars as pl

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

print(
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
)

shape: (21, 2)
┌───────────────────────────┬───────┐
│ event_type                ┆ len   │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ market_commentary         ┆ 32108 │
│ earnings_fundamental      ┆ 26333 │
│ business_development      ┆ 10352 │
│ dividend                  ┆ 8810  │
│ dilution_corporate_action ┆ 7551  │
│ …                         ┆ …     │
│ macro_rate                ┆ 1383  │
│ debt_financing            ┆ 1291  │
│ macro_currency            ┆ 1033  │
│ credit_rating             ┆ 726   │
│ stock_split               ┆ 551   │
└───────────────────────────┴───────┘

## Audit taxonomy event

In [3]:
import polars as pl
from pathlib import Path

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")
out = Path("data/news/event_intelligence/audit_samples")
out.mkdir(parents=True, exist_ok=True)

event_types = (
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
      .get_column("event_type")
      .to_list()
)

for et in event_types:
    safe = et.replace("/", "_").replace(" ", "_")
    (
        df.filter(pl.col("event_type") == et)
          .select([
              "news_date",
              "source",
              "news_category",
              "title",
              "ticker",
              "company_name",
              "sector",
              "event_type",
              "event_side",
              "impact_channel",
              "materiality_score",
              "uncertainty_score",
          ])
          .head(50)
          .write_csv(out / f"sample_{safe}.csv")
    )

print(f"Saved audit samples to: {out}")

Saved audit samples to: data/news/event_intelligence/audit_samples

### sample audit after rebuild

In [7]:
import polars as pl
from pathlib import Path

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

out = Path("data/news/event_intelligence/audit_samples_after_fix")
out.mkdir(parents=True, exist_ok=True)

for et in df.group_by("event_type").len().sort("len", descending=True)["event_type"].to_list():
    safe = et.replace("/", "_").replace(" ", "_")
    (
        df.filter(pl.col("event_type") == et)
          .select([
              "news_date",
              "source",
              "news_category",
              "title",
              "ticker",
              "company_name",
              "sector",
              "event_type",
              "event_side",
              "impact_channel",
              "materiality_score",
              "uncertainty_score",
          ])
          .head(50)
          .write_csv(out / f"sample_{safe}.csv")
    )

print("saved:", out)

saved: data/news/event_intelligence/audit_samples_after_fix

In [2]:
import polars as pl
from pathlib import Path

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

out = Path("data/news/event_intelligence/audit_samples_after_v37")
out.mkdir(parents=True, exist_ok=True)

event_types = (
    df.group_by("event_type")
      .len()
      .sort("len", descending=True)
      .get_column("event_type")
      .to_list()
)

for et in event_types:
    safe = et.replace("/", "_").replace(" ", "_")
    (
        df.filter(pl.col("event_type") == et)
          .select([
              "news_date",
              "source",
              "news_category",
              "title",
              "ticker",
              "company_name",
              "sector",
              "event_type",
              "event_side",
              "impact_channel",
              "materiality_score",
              "uncertainty_score",
          ])
          .head(50)
          .write_csv(out / f"sample_{safe}.csv")
    )

print("saved:", out)

saved: data/news/event_intelligence/audit_samples_after_v37

In [ ]:
import polars as pl
from pathlib import Path

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")

out = Path("data/news/event_intelligence/audit_samples_after_v38")
out.mkdir(parents=True, exist_ok=True)

for et in df.group_by("event_type").len().sort("len", descending=True)["event_type"].to_list():
    safe = et.replace("/", "_").replace(" ", "_")
    (
        df.filter(pl.col("event_type") == et)
          .select([
              "news_date",
              "source",
              "news_category",
              "title",
              "ticker",
              "company_name",
              "sector",
              "event_type",
              "event_side",
              "impact_channel",
              "materiality_score",
              "uncertainty_score",
          ])
          .head(50)
          .write_csv(out / f"sample_{safe}.csv")
    )

print("saved:", out)

## Live feature view dan label view

In [5]:
import polars as pl
from pathlib import Path

base = Path("data/news/event_intelligence")
df = pl.read_parquet(base / "news_event_intelligence_dataset.parquet")

id_cols = [
    "event_row_id", "article_id", "news_date", "entry_date", "ticker",
]

metadata_cols = [
    "source", "news_category",
    "sector", "subsector", "industry", "subindustry", "listing_board",
]

event_cols = [
    "event_scope", "event_type", "event_side", "impact_channel",
    "materiality_label", "materiality_score",
    "news_intensity_score", "uncertainty_score", "novelty_score",
    "bullish_keyword_hits", "bearish_keyword_hits", "uncertainty_keyword_hits",
    "same_event_seen_so_far",
]

live_market_cols = [
    "open", "high", "low", "close", "volume", "value", "frequency",
    "foreign_buy", "foreign_sell", "daily_ret", "is_zero_volume",
    "avg_volume_20d", "volume_ratio", "bwd_volatility_20d", "drawdown_20d",
]

bwd_cols = [
    c for c in df.columns
    if c.startswith("bwd_ret_") or c.startswith("bwd_volume_ratio_")
]

live_cols = [
    c for c in id_cols + metadata_cols + event_cols + live_market_cols + bwd_cols
    if c in df.columns
]

label_cols = [
    c for c in df.columns
    if (
        c.startswith("fwd_ret_")
        or c.startswith("ihsg_fwd_ret_")
        or c.startswith("sector_fwd_ret_")
        or c.startswith("market_alpha_")
        or c.startswith("sector_alpha_")
        or c.startswith("volatility_shock_")
        or c.startswith("mae_")
        or c.startswith("mfe_")
        or c.endswith("_label_5d")
        or c == "reaction_label_5d"
    )
]

label_view_cols = [c for c in id_cols + label_cols if c in df.columns]

live = df.select(live_cols)
labels = df.select(label_view_cols)

live.write_parquet(base / "news_event_live_features.parquet")
labels.write_parquet(base / "news_event_training_labels.parquet")

live.head(10).write_csv(base / "sample_live_features_10.csv")
labels.head(10).write_csv(base / "sample_training_labels_10.csv")

print("Full dataset:", df.shape)
print("Live features:", live.shape)
print("Training labels:", labels.shape)

Full dataset: (127123, 122)
Live features: (127123, 52)
Training labels: (127123, 63)

# Event study detail

In [6]:
import polars as pl
from pathlib import Path

df = pl.read_parquet("data/news/event_intelligence/news_event_intelligence_dataset.parquet")
out = Path("data/news/event_intelligence/report")
out.mkdir(parents=True, exist_ok=True)

def event_study(group_cols, filename):
    report = (
        df.group_by(group_cols)
          .agg([
              pl.len().alias("n_rows"),
              pl.col("article_id").n_unique().alias("n_articles"),
              pl.col("ticker").n_unique().alias("n_tickers"),

              pl.col("sector_alpha_5d").mean().alias("avg_sector_alpha_5d"),
              pl.col("sector_alpha_5d").median().alias("median_sector_alpha_5d"),
              (pl.col("sector_alpha_5d") > 0).mean().alias("hit_rate_sector_alpha_5d"),
              (pl.col("sector_alpha_5d") > 0.01).mean().alias("hit_rate_sector_alpha_gt_1pct_5d"),

              pl.col("market_alpha_5d").mean().alias("avg_market_alpha_5d"),
              (pl.col("market_alpha_5d") > 0).mean().alias("hit_rate_market_alpha_5d"),

              pl.col("volatility_shock_5d").mean().alias("avg_volatility_shock_5d"),
              (pl.col("volatility_shock_5d") > 1.5).mean().alias("volatility_shock_rate_5d"),

              pl.col("mae_5d").mean().alias("avg_mae_5d"),
              pl.col("mfe_5d").mean().alias("avg_mfe_5d"),

              (pl.col("sentiment_trap_label_5d") == 1).mean().alias("sentiment_trap_rate_5d"),
              (pl.col("delayed_reaction_label_5d") == 1).mean().alias("delayed_reaction_rate_5d"),
              (pl.col("acceleration_trigger_label_5d") == 1).mean().alias("acceleration_trigger_rate_5d"),
          ])
          .filter(pl.col("n_rows") >= 30)
          .sort("n_rows", descending=True)
    )
    report.write_csv(out / filename)
    return report

event_study(["event_type"], "event_study_by_event_type_detailed.csv")
event_study(["event_type", "event_side"], "event_study_by_event_type_side.csv")
event_study(["event_type", "sector"], "event_study_by_event_type_sector.csv")
event_study(["event_type", "news_category"], "event_study_by_event_type_category.csv")

print("saved to", out)

saved to data/news/event_intelligence/report